GET http://localhost:3001/calendar

###

POST http://localhost:3001/calendar/new
Content-Type: application/json

{
    "content": "content-check",
    "weather": "Rainy"
}

###
DELETE http://localhost:3001/calendar/delete/64386171543adf931606c7b0
