GET http://localhost:3001/calendar

###

POST http://localhost:3001/calendar/new
Content-Type: application/json

{
    "text": "Friday"
}

###
DELETE http://localhost:3001/calendar/delete/642a496815af14e721a0e6aa
